### ISSUE TITLE
[BUG] in HeteroFL, the accuracy of the global model does not change

### ISSUE THREAD

**Issue by wangxm233** [TL-System/plato#313]
**Describe the bug**
the results of HeteroFL in examples seem doesn't right, the accuracy of the global model does not change

**To Reproduce**
python examples/heterofl/heterofl.py -c examples/heterofl/heterofl_resnet18_dynamic.yml

**Screenshots**
![image](https://user-images.githubusercontent.com/46741563/233774091-7fc26da2-13e5-469e-8aa5-f26f4813e3a6.png)

**Additional context**
Compared to FedRolex, the HeteroFL takes much more time on model aggregation, which is weird too, the two methods have the same aggregation steps based on papers.
the HeteroFL aggregation:
![image](https://user-images.githubusercontent.com/46741563/233773984-aca5288e-d161-4d08-a1f0-19ae275674d3.png)
the FedRolex aggregation:
![image](https://user-images.githubusercontent.com/46741563/233774029-8b7e7d0c-16d4-4b2a-8bca-37e1665a64e6.png)

**Comment by dixiyao** [comment]
@wangxm233 In the implementation of HeteroFL, it contains HeteroFL algorithm according to their paper including the statistical batch normalization. This example shows that statistical batch normalization is a poor design (e.g. may not converge) when the structures of sub models are randomly sampled. 

On the other hand, in the example of FedRolex, where we give an example of removing the sBN module. You can disable the sBN module in the HeteroFL by set parameter ```parameters.model.track``` to ```false```  in the configuration file and annotate function ```weights_aggregated``` and ```clients_processed``` in ```heterofl_server.py``` or refer to the implementation in FedRolex where sBN module is disabled.

### Additional Context
More time spent during mode aggregation is caused by the process of doing statistical batch normalization operations.
